# Generated by Django 3.0.8 on 2020-09-22 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_listing',
            name='picture',
            field=models.TextField(blank=True, max_length=150),
        ),
    ]
