# Generated by Django 3.0.8 on 2020-09-22 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction_listing_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listing',
            name='picture',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
