# Generated by Django 3.0.8 on 2020-09-22 20:26

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20200922_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_listing',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auction_listing',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2020, 9, 22, 20, 26, 22, 975643, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
