# Generated by Django 3.0.8 on 2020-09-23 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20200922_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_listing',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
